/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Tokens Totum
        surface: "var(--surface)",
        neutral: "var(--neutral)",
        elevated: "var(--elevated)",
        "hover-surface": "var(--hover-surface)",
        "warm-rust": "var(--warm-rust)",
        "cool-graphite": "var(--cool-graphite)",
        "brand-red-bright": "var(--brand-red-bright)",
        "brand-red-vibrant": "var(--brand-red-vibrant)",
        "brand-red-light": "var(--brand-red-light)",
        "brand-purple-bright": "var(--brand-purple-bright)",
        tertiary: "var(--tertiary)",
        success: "var(--success)",
        "text-soft": "var(--white-soft)",
        // shadcn aliases
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        pill: "9999px",
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "display-large": ["54px", { lineHeight: "1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "section-heading": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" }],
        "subheading-lg": ["38px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "300" }],
        "subheading": ["32px", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "300" }],
        "body-lg": ["20px", { lineHeight: "1.25", fontWeight: "300" }],
      },
      letterSpacing: {
        title: "-0.02em",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
